on:
  push:
    branches:
      - main
      - dev

name: docs

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        r: ['3.6']

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        with:
            r-version: ${{ matrix.r }}

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Ubuntu config
        run: |
          sudo add-apt-repository ppa:ubuntugis/ppa
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev libudunits2-dev libgdal-dev libgeos-dev libproj-dev libmagick++-dev libavfilter-dev libharfbuzz-dev
      - name: Install dependencies
        env:
          R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
        run: Rscript -e "install.packages(c('remotes', 'rcmdcheck', 'covr', 'pkgdown'))" -e "remotes::install_deps(dependencies = TRUE)"

      - name: Install package
        run: R CMD INSTALL .

      - name: Deploy package
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          Rscript -e 'install.packages("pkgdown")'
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE)'
